FROM adoptopenjdk:11-jdk-hotspot as builder

WORKDIR /app

COPY pom.xml .

RUN --mount=type=cache,target=/root/.m2 mvn dependency:go-offline

COPY src ./src

RUN --mount=type=cache,target=/root/.m2 mvn package -DskipTests

FROM adoptopenjdk:11-jre-hotspot

WORKDIR /app

COPY --from=builder /app/target/classes ./classes

ENV SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-chj11ld269v2e2crp9eg-a:5432/devhouse
ENV SPRING_DATASOURCE_USERNAME=your-database-payr1ch
ENV SPRING_DATASOURCE_PASSWORD=your-database-4UG31Y5r5MweZCNXZkwYM6uP7BrZ2FSb

EXPOSE 8080

CMD ["java", "-cp", "classes", "com.example.devhouse.DevhouseApplication"]
